import Veil.Frontend.DSL.Action.DoElab.Context
import Veil.Frontend.DSL.Action.Syntax
import Veil.Frontend.DSL.Action.TupleUpdate

open Lean Elab Term Meta Lean.Parser
open Lean.Elab.Do
open Lean.Parser.Term

namespace Veil
namespace Action.DoElab

/-! ## Pre-elaboration: wrapping and control information -/

/-- Internal wrapper keeping application-shaped (`r x := v`) and structure
access (`f.q := true`) Veil writes (pure and arrow assignments alike) out of
Lean's ordinary reassignment pattern analysis. The wrapped syntax is produced
is not part of Veil's surface language. -/
scoped syntax (name := stateAssignWrapper) "veil_state_assign% " doElem : doElem

/-- `f.x := v` OR `r x := v` -/
private def assignmentNeedsWrapper (lhs : Term) : Bool :=
  (lhs.raw.isIdent && !lhs.raw.getId.isAtomic) || lhs.isApp?.isSome

private def wrapAssignment (stx : Syntax) : TermElabM Syntax := do
  let elem : DoElem := ⟨stx⟩
  match elem with
  | `(doReassign| $lhs:term $[: $_]? := $_)
  | `(doReassignArrow| $lhs:term $[: $_]? ← $_ $[| $_ $[$_]?]?) =>
    if assignmentNeedsWrapper lhs then
      return (← `(doElem| veil_state_assign% $elem:doElem)).raw
    return stx
  | _ => return stx

/- Hide application-shaped state writes behind a private `doElem` kind before
Lean infers reaching-definition control information. Lean otherwise interprets
`r x := v` as a reassignment pattern and rejects the application before Veil's
elaboration handler can run. -/
mutual
  /-- Walk the action syntax bottom-up, preserving quotation boundaries. -/
  private partial def rewriteAssignments (stx : Syntax)
      (inQuotation : Bool) : TermElabM Syntax := do
    let .node info kind args := stx | return stx
    let childInQuotation := Action.childrenAreQuoted stx inQuotation
    let firstChildIsDoElem :=
      kind == ``Lean.Parser.Term.doSeqItem && !childInQuotation
    let args ← args.mapIdxM fun i child =>
      if firstChildIsDoElem && i == 0 then
        expandAndRewriteDoElem child
      else
        rewriteAssignments child childInQuotation
    let rebuilt := Syntax.node info kind args
    if inQuotation then pure rebuilt else wrapAssignment rebuilt

  /-- (Recursively) macro-expand a surface `doElem` before looking for
  assignments generated by the expansion. -/
  private partial def expandAndRewriteDoElem (stx : Syntax) : TermElabM Syntax := do
    let env ← getEnv
    let elem : DoElem := ⟨stx⟩
    if let some (_decl, expanded?) ← liftMacroM (expandMacroImpl? env elem) then
      let expanded ← liftMacroM <| liftExcept expanded?
      expandAndRewriteDoElem expanded
    else
      rewriteAssignments stx false
end

/-- Rewrite application-shaped (`r x := v`) and structure access (`f.q :=
true`) assignments before Lean computes `do` control information. This is so
Lean's assignment elaborator, which runs first, does not reject them: Veil must
transform them into assignments Lean accepts. -/
def prepareStateAssignments (stx : Syntax) : TermElabM Syntax :=
  rewriteAssignments stx false

/-- The target (left-hand side) of an assignment-shaped statement: plain
(`:=`), arrow (`←`), or havoc (`:= *`). The single source of truth for what
counts as an assignment shape — pre-elaboration validation (`Entry.lean`) and
control-info reporting below must never disagree about it. -/
def assignmentLhs? (elem : DoElem) : Option Term :=
  match elem with
  | `(doReassign| $lhs:term $[: $_]? := $_) => some lhs
  | `(doReassignArrow| $lhs:term $[: $_]? ← $_ $[| $_ $[$_]?]?) => some lhs
  | `(doElem| $lhs:term := *) => some lhs
  | _ => none

/-- The head identifier of an assignment-shaped statement's target (wrapped
assignments and havoc). -/
private def assignmentTargetHead? (elem : DoElem) : Option Ident :=
  assignmentLhs? elem |>.bind fun lhs =>
    if lhs.raw.isIdent then
      some ⟨lhs.raw⟩
    else
      lhs.isApp?.map fun (head, _) => head

/-- Wrapped assignments must still report their target as reassigned: Lean
threads `let mut` locals through branch join points based on this set, and an
application-shaped target can resolve to a local (e.g. `m true := true`). The
target cannot be resolved this early, so report the head name conservatively:
over-reporting a state component is harmless (its write flows through the
monad), while under-reporting a local silently drops the write at the next
join. -/
@[doElem_control_info stateAssignWrapper]
def assignmentControlInfo : ControlInfoHandler := fun stx => do
  let `(doElem| veil_state_assign% $elem:doElem) := stx | throwUnsupportedSyntax
  let some head := assignmentTargetHead? elem | return ControlInfo.pure
  /- This is the same composition used by Lean's
  `InferControlInfo.ofLetOrReassignArrow`, except that we supply the target
  head directly instead of asking Lean to interpret an application-shaped
  target as a reassignment pattern. -/
  match elem with
  | `(doReassign| $_:term $[: $_]? := $_) =>
    InferControlInfo.ofLetOrReassign #[head] none none none
  | `(doReassignArrow| $decl:doIdDecl) =>
    match decl with
    | `(doIdDecl| $_:ident $[: $_]? ← $rhs:doElem) =>
      InferControlInfo.ofLetOrReassign #[head] (some rhs) none none
    | _ => throwUnsupportedSyntax
  | `(doReassignArrow| $decl:doPatDecl) =>
    match decl with
    | `(doPatDecl| $_:term $[: $_]? ← $rhs:doElem $[| $otherwise? $[$body??]?]?) =>
      InferControlInfo.ofLetOrReassign #[head] (some rhs) otherwise? body??.join
    | _ => throwUnsupportedSyntax
  | _ => throwUnsupportedSyntax

/-- Havoc reassigns its target when the target resolves to a `let mut` local,
so it reports the head conservatively, like wrapped assignments. -/
@[doElem_control_info havocAssignment]
def havocControlInfo : ControlInfoHandler := fun stx => do
  let some head := assignmentTargetHead? stx | return ControlInfo.pure
  return { ControlInfo.pure with reassigns := ({} : NameSet).insert head.getId }

/-! ## Targets: parsing and resolution -/

private structure Target where
  /-- The hygienic source identifier, used for local-variable resolution. -/
  head : Ident
  /-- The unscoped name used only after local resolution, for module-component
  lookup and state structure updates. -/
  componentName : Name
  args : Array Term := #[]

private inductive ResolvedTarget where
  | local
  | state (component : StateComponent)

private def parseTargetHead (head : Ident) (args : Array Term := #[]) :
    TermElabM Target := do
  let name := head.getId.eraseMacroScopes
  unless name.isAtomic do
    throwErrorAt head
      "qualified state assignments are not supported; assign through an unqualified state component name"
  return { head, componentName := name, args }

private def parseTarget (lhs : Term) : TermElabM Target := do
  match lhs with
  | `(term| $id:ident) => parseTargetHead id
  | _ =>
    let some (head, args) := lhs.isApp?
      | throwUnsupportedSyntax
    parseTargetHead head args

private def parseReassign (stx : DoElem) : TermElabM (Target × Option Term × Term) := do
  match stx with
  | `(doReassign| $id:ident $[: $ty:term]? := $rhs:term) =>
    return (← parseTargetHead id, ty, rhs)
  | `(doReassign| $lhs:term $[: $ty:term]? := $rhs:term) =>
    return (← parseTarget lhs, ty, rhs)
  | _ => throwError m!"internal Veil assignment parser mismatch:{indentD stx} raw: {stx.raw}"

private structure ParsedReassignArrow where
  target : Target
  type? : Option Term
  rhs : DoElem
  /-- Whether the statement carries a fallback branch (`pat ← e | fb`). -/
  hasFallback : Bool

private def parseReassignArrow (stx : DoElem) : TermElabM ParsedReassignArrow := do
  match stx with
  | `(doReassignArrow| $decl:doIdDecl) =>
    match decl with
    | `(doIdDecl| $id:ident $[: $ty:term]? ← $rhs:doElem) =>
      return { target := ← parseTargetHead id, type? := ty, rhs, hasFallback := false }
    | _ => throwUnsupportedSyntax
  | `(doReassignArrow| $decl:doPatDecl) =>
    match decl with
    | `(doPatDecl| $lhs:term $[: $ty:term]? ← $rhs:doElem | $_ $[$_]? ) =>
      return { target := ← parseTarget lhs, type? := ty, rhs, hasFallback := true }
    | `(doPatDecl| $lhs:term $[: $ty:term]? ← $rhs:doElem) =>
      return { target := ← parseTarget lhs, type? := ty, rhs, hasFallback := false }
    | _ => throwUnsupportedSyntax
  | _ => throwUnsupportedSyntax

/-- Run `x`, mapping `throwUnsupportedSyntax` to `none`. -/
private def catchUnsupported? (x : DoElabM α) : DoElabM (Option α) :=
  catchInternalId unsupportedSyntaxExceptionId (some <$> x) (fun _ => pure none)

/-- Fail because the assignment target is a local that is not `let mut`,
pointing out shadowing when that is the likely cause. -/
private def throwImmutableLocalTarget (target : Target) (mod : Module) : DoElabM α := do
  if mod.mutableComponents.any (·.name == target.componentName) then
    throwErrorAt target.head
      "this immutable local shadows a mutable state component with the same name; rename the local to assign to the state component"
  throwErrorAt target.head
    "this local is immutable; only variables declared with `let mut` can be assigned"

/-- Resolve `target` to a state component, or fail with `onMissing`. -/
private def resolveStateComponent (mod : Module) (target : Target)
    (onMissing : MessageData) : DoElabM StateComponent := do
  let some component := mod.signature.find? (·.name == target.componentName)
    | throwErrorAt target.head onMissing
  unless component.isMutable do mod.throwIfImmutable component.name
  return component

/-- Decide what the assignment target's head refers to. A user-visible local
of that name always takes precedence over a state component: it resolves to
`.local` if it is a `let mut` variable, and is an error otherwise. Only when
no such local exists is the target resolved as a mutable state component. -/
private def resolveAssignmentTarget (ctx : Context) (target : Target) : DoElabM ResolvedTarget := do
  if (← findUserLocal? target.head.getId).isSome then
    unless (← findMutVar? target.head.getId).isSome do
      throwImmutableLocalTarget target ctx.mod
    return .local
  let component ← resolveStateComponent ctx.mod target
    m!"assignment target `{target.componentName}` is not a mutable state component or a `let mut` local"
  return .state component

/-! ## Capitalized-index analysis -/

private def implicitCapital? (ctx : Context) (arg : Term) : TermElabM (Option Name) := do
  let `(term| $id:ident) := arg | return none
  unless isCapital id.getId do return none
  if let some userDecl ← findUserLocal? id.getId then
    let category := if ctx.parameters.contains userDecl.fvarId then "parameter" else "local"
    logWarningAt id m!"capitalized index `{id.getId}` resolves to {category} `{id.getId}`; this is a point update, not a universal update"
    return none
  if let some component := ctx.mod.signature.find? (·.name == id.getId) then
    let category := if component.isMutable then "mutable state component" else "immutable theory component"
    logWarningAt id m!"capitalized index `{id.getId}` resolves to {category} `{id.getId}`; this is a point update, not a universal update"
    return none
  -- Anything else is an Ivy universal, even a name matching a Lean global:
  -- action semantics must not depend on imports. Warn about the shadowing.
  unless (← resolveGlobalName (enableLog := false) id.getId).isEmpty do
    logWarningAt id m!"capitalized index `{id.getId}` is a universal index and shadows the Lean declaration `{id.getId}`; to use the declaration as a point index, bind it to a non-capitalized local first"
  return some id.getId

private def implicitCapitals (ctx : Context) (args : Array Term) : TermElabM (Array (Option Name)) :=
  args.mapM (implicitCapital? ctx)

private def checkRepeatedCapitals (target : Target)
    (caps : Array (Option Name)) : TermElabM Unit :=
  discard <| caps.zipIdx.foldlM (init := ({} : NameSet)) fun seen (cap?, i) => do
    let some name := cap? | return seen
    if seen.contains name then
      throwErrorAt target.args[i]!
        "you cannot use the same capitalized identifier more than once in an assignment; diagonal updates are not yet supported"
    return seen.insert name

/-! ## Compiling assignments -/

/-- Check a state-assignment annotation against the type at the complete target. -/
private def checkStateTargetTypeAscription (component : StateComponent)
    (target : Target) (type? : Option Term) : DoElabM Unit := do
  let some typeStx := type? | return
  let domains := component.domainTerms
  let codomain := component.codomainTerm
  /- Let the generated application report an over-application; manufacturing
  a target type after too many arguments would only hide that better error. -/
  if domains.size < target.args.size then return
  let targetTypeStx ← mkArrowStx (domains.drop target.args.size).toList (some codomain)
  let annotated ← Term.elabType typeStx
  let targetType ← Term.elabType targetTypeStx
  unless ← isDefEq annotated targetType do
    throwErrorAt typeStx m!"state assignment annotation `{typeStx}` does not match the target type `{targetTypeStx}` at this application of component `{component.name}`"

/-- Elaborate each non-capitalized index once (at statement scope) and bind it
to an implementation-detail `let`. This ensures that in `r N (f N) := v`, the
`N` at which `f N` is evaluated is NOT the universal binder introduced by the
capital. -/
private partial def withPinnedTargetArgs (target : Target)
    (caps : Array (Option Name)) (i : Nat)
    (k : Target → DoElabM Expr) : DoElabM Expr := do
  if i < target.args.size then
    if caps[i]!.isSome then
      withPinnedTargetArgs target caps (i + 1) k
    else
      let arg := target.args[i]!
      let value ← Term.elabTerm arg none
      let ty ← inferType value
      let name ← mkFreshUserName
        (mkVeilImplementationDetailName <| Name.mkSimple s!"index_{i}")
      mapLetDecl name ty value (kind := .implDetail) fun _ =>
        withPinnedTargetArgs { target with args := target.args.set! i (mkIdent name) }
          caps (i + 1) k
  else
    k target

/-- Build the `replacement` argument of `setSingle`: a function over the
field's domain computing the written value. When the write is shallower than
the entry (`codomainArgs` nonempty), the entry is updated pointwise at those
arguments rather than replaced. -/
private def mkAssignmentReplacement (component : StateComponent)
    (domainArgs codomainArgs : Array Term) (capitals : Array (Option Name))
    (rhs : Term) : TermElabM Term := do
  let funBinders : Array (TSyntax ``Lean.Parser.Term.funBinder) ←
    domainArgs.mapIdxM fun i arg =>
      if let some name := capitals[i]! then
        `(Term.funBinder| $(mkIdentFrom arg name):ident)
      else
        `(Term.funBinder| _)
  let body ←
    if codomainArgs.isEmpty then
      pure rhs
    else
      let old := Syntax.mkApp (← `($(mkIdent component.name):ident)) domainArgs
      `($old _[ $[$codomainArgs],* ↦ $rhs ]_)
  mkFunSyntax funBinders body

/-- Build the `pattern` argument of `setSingle`: one `Option` slot per domain
coordinate — `some idx` for a fixed index, `none` for a capitalized one —
padded with `none`s to the field's full arity and normalized at elaboration
time so the later `set`/`get` simp phases can match it. -/
private def mkAssignmentPattern (mod : Module) (component : StateComponent)
    (domainArgs : Array Term) (capitals : Array (Option Name)) : TermElabM Term := do
  let options ← domainArgs.mapIdxM fun i arg =>
    if capitals[i]!.isSome then
      `($(mkIdent ``Option.none))
    else
      `(($(mkIdent ``Option.some) $arg))
  let domain ← `($(fieldLabelToDomain stateName)
    $(← mod.uninterpretedParamIdents):ident*
    $(mkIdent <| structureFieldLabelTypeName stateName ++ component.name):ident)
  `(veil_dsimp% +$(mkIdent `instances) [$(mkIdent `fieldRepresentationPatSimp)]
    ($(mkIdent ``FieldUpdatePat.pad) ($domain)
      $(Syntax.mkNatLit options.size) $options*))

/-- Emit the monadic write for a state assignment whose fixed indices were
already pinned by `withPinnedTargetArgs`, so each index is a let-bound fvar that
can safely appear in several generated positions.

The target's arguments are split at the component's arity into domain
coordinates and a codomain residue, from which the two halves of the update
are built: `mkAssignmentPattern` (which entries change) and
`mkAssignmentReplacement` (the value they receive). The field's new value,
`(fieldRepresentation _).setSingle pattern replacement f_conc`, is computed
from the statement's current concrete field view `f_conc` and bound once as an
implementation-detail `let`, so the write itself stays a trivial structure
update the WP simplifier can digest (via `VeilM.wp_modify`/`wp_modify'`):
`modify fun st => { st with f := __veil_bind_f }`.

The statement produces no value (`ensureUnitAt`), and the returned expression
is the entire remaining block: the continuation `dec` is elaborated after the
write. `ref` and the target's head only position diagnostics and hovers on the
original assignment syntax. -/
private def elabPinnedStateAssignment (mod : Module) (component : StateComponent)
    (target : Target) (caps : Array (Option Name)) (rhs : Term)
    (ref : Syntax) (dec : DoElemCont) : DoElabM Expr := do
  let domainSize := component.domainTerms.size
  let domainArgs := target.args.take domainSize
  let replacement ← mkAssignmentReplacement component domainArgs
    (target.args.drop domainSize) (caps.take domainSize) rhs
  let pattern ← mkAssignmentPattern mod component domainArgs (caps.take domainSize)

  let concrete := currentConcreteFieldIdent component.name
  let setTerm ←
    `(($fieldRepresentation _).$(mkIdent `setSingle) ($pattern) ($replacement) $concrete)
  let setValue ← Term.elabTerm setTerm none
  let setType ← inferType setValue
  let bindName ← mkFreshUserName
    (mkVeilImplementationDetailName <| Name.mkSimple s!"bind_{component.name}")
  mapLetDecl bindName setType setValue (kind := .implDetail) fun _ => do
    let st := mkIdent `st
    let updateTerm ← withRef ref
      `($(mkIdent ``modify) (fun $st:ident =>
        {$st:ident with $(mkIdentFrom target.head component.name):ident := $(mkIdent bindName)}))
    let updateElem ← `(doElem| $updateTerm:term)
    Lean.Elab.Do.elabDoExpr updateElem (← dec.ensureUnitAt ref)

/-- Compile a state assignment whose capital analysis (`caps`) has already
run, pinning the fixed indices first. -/
private def elabAnalyzedStateAssignment (mod : Module) (component : StateComponent)
    (target : Target) (caps : Array (Option Name)) (rhs : Term)
    (ref : Syntax) (dec : DoElemCont) : DoElabM Expr :=
  withPinnedTargetArgs target caps 0 fun target =>
    elabPinnedStateAssignment mod component target caps rhs ref dec

private def elabStateAssignment (ctx : Context) (component : StateComponent)
    (target : Target) (rhs : Term) (ref : Syntax) (dec : DoElemCont) : DoElabM Expr := do
  let caps ← implicitCapitals ctx target.args
  checkRepeatedCapitals target caps
  elabAnalyzedStateAssignment ctx.mod component target caps rhs ref dec

/-- Compile an indexed local update whose capital analysis (`caps`) already
ran. The tuple-update macro classifies capitals by spelling alone, so every
point index — including a capital that *resolves* to a point, such as a
parameter — is pinned to a fresh non-capital implementation-detail local
first; only resolution-checked universal capitals stay bare. -/
private def elabAnalyzedLocalAssignment (target : Target)
    (caps : Array (Option Name)) (rhs : Term) (ref : Syntax)
    (dec : DoElemCont) : DoElabM Expr := do
  if target.args.isEmpty then
    let elem ← `(doElem| $(target.head):ident := $rhs:term)
    Lean.Elab.Do.elabDoReassign elem dec
  else
    withPinnedTargetArgs target caps 0 fun target => do
      let updated ← `($(target.head):ident _[ $[$(target.args)],* ↦ $rhs:term ]_)
      let elem ← withRef ref `(doElem| $(target.head):ident := $updated:term)
      Lean.Elab.Do.elabDoReassign elem dec

private def elabLocalAssignment (ctx : Context) (target : Target) (rhs : Term)
    (ref : Syntax) (dec : DoElemCont) : DoElabM Expr := do
  let caps ← implicitCapitals ctx target.args
  checkRepeatedCapitals target caps
  elabAnalyzedLocalAssignment target caps rhs ref dec

private def elabPureAssignment (ctx : Context) (target : Target)
    (type? : Option Term) (rhs : Term)
    (stx : DoElem) (dec : DoElemCont) : DoElabM Expr := do
  let rhs ← match type? with
    | none => pure rhs
    | some typeStx =>
      /- Mirror Lean's `pushTypeIntoReassignment` from `Lean/Elab/BuiltinDo/Let.lean`,
      which pushes a reassignment pattern's inferred type onto its RHS.
      Veil handles application-shaped targets before Lean can do so,
      hence `r x : τ := v` must explicitly elaborate the written
      value as `(v : τ)`. -/
      `(($rhs : $typeStx))
  match ← resolveAssignmentTarget ctx target with
  | .local => elabLocalAssignment ctx target rhs stx dec
  | .state component =>
    checkStateTargetTypeAscription component target type?
    elabStateAssignment ctx component target rhs stx dec

/-! ## Assignment statement handlers -/

@[doElem_elab Lean.Parser.Term.doReassign]
def elabStateReassign : DoElab := fun stx dec => do
  let ctx ← requireVeilDoBlock
  let some (target, type?, rhs) ← catchUnsupported? (parseReassign stx)
    | -- Pattern-shaped targets are Lean's business, but they may write state.
      Lean.Elab.Do.elabDoReassign stx (openStateAfter ctx.mod dec)
  elabPureAssignment ctx target type? rhs stx (openStateAfter ctx.mod dec)

private def withArrowResult (target : Target) (type? : Option Term)
    (rhs : DoElem) (ref : Syntax)
    (k : Term → DoElabM Expr) : DoElabM Expr := do
  let name ← mkFreshUserName
    (mkVeilImplementationDetailName <| Name.mkSimple s!"arrow_{target.componentName}")
  /- `r x : τ ← action` becomes `let tmp : τ ← action; r x := tmp`:
  the annotation constrains the action's result, which is the value written at
  the complete target. -/
  elabDoIdDecl (mkIdentFrom ref name) type? rhs (k (mkIdent name))

@[doElem_elab Lean.Parser.Term.doReassignArrow]
def elabStateReassignArrow : DoElab := fun stx dec => do
  let ctx ← requireVeilDoBlock
  let some { target, type?, rhs, hasFallback } ← catchUnsupported? (parseReassignArrow stx)
    | -- Pattern-shaped targets are Lean's business (see `elabStateReassign`).
      Lean.Elab.Do.elabDoReassignArrow stx (openStateAfter ctx.mod dec)
  let dec := openStateAfter ctx.mod dec
  do
    match ← resolveAssignmentTarget ctx target with
    | .local =>
      if hasFallback then
        if target.args.isEmpty then
          return ← Lean.Elab.Do.elabDoReassignArrow stx dec
        throwErrorAt stx "fallback branches are not supported on indexed Veil assignments"
      if target.args.isEmpty then
        return ← Lean.Elab.Do.elabDoReassignArrow stx dec
      withArrowResult target type? rhs stx fun value =>
        -- The index terms must read post-call state (as in `.state` below).
        openStateAround ctx.mod <|
          elabLocalAssignment ctx target value stx dec
    | .state component =>
      if hasFallback then
        throwErrorAt stx "fallback branches are not supported on Veil state arrow assignments"
      checkStateTargetTypeAscription component target type?
      withArrowResult target type? rhs stx fun value =>
        openStateAround ctx.mod <|
          elabStateAssignment ctx component target value stx dec

@[doElem_elab stateAssignWrapper]
def elabWrappedAssignment : DoElab := fun stx dec => do
  let `(doElem| veil_state_assign% $original:doElem) := stx | throwUnsupportedSyntax
  if original.raw.isOfKind ``Lean.Parser.Term.doReassignArrow then
    elabStateReassignArrow original dec
  else
    elabStateReassign original dec

/-! ## Havoc -/

/-- Bind `fresh ← MonadNonDet.pick pickType` and hand `k` the havoc's
right-hand side, `fresh` applied to `appliedArgs`. -/
private def withFreshPick (target : Target) (pickType : Term)
    (appliedArgs : Array Term) (k : Term → DoElabM Expr) : DoElabM Expr := do
  let freshName ← mkFreshUserName
    (Name.mkSimple s!"pick_{target.componentName}")
  let fresh := mkIdentFrom target.head freshName
  let pickTerm ← `($(mkIdent ``MonadNonDet.pick) $pickType)
  let pickElem ← `(doElem| $pickTerm:term)
  elabDoIdDecl fresh none pickElem do
    k (Syntax.mkApp fresh appliedArgs)

/-- The narrowed type a havoc picks: one binder of `type` is stripped per
supplied index, and the universal capitals' domains are kept, curried onto
what remains — so a point index never widens the pick, and unsupplied
trailing dimensions stay part of it. Fails if `type` accepts fewer indices
than supplied or depends on their values. -/
private def havocPickType (target : Target) (ty : Expr)
    (caps : Array (Option Name)) : DoElabM Term := do
  Meta.forallBoundedTelescope ty (some caps.size) fun xs body => do
    unless xs.size == caps.size do
      throwErrorAt target.head
        m!"cannot havoc `{target.componentName}`: its type{indentExpr ty}\ndoes not accept this many index arguments"
    let capitalDomains ← xs.zipIdx.filterMapM fun (x, i) => do
      if caps[i]!.isSome then return some (← inferType x) else return none
    let pickType ← liftM (mkArrowN capitalDomains body)
    if xs.any fun x => pickType.containsFVar x.fvarId! then
      throwErrorAt target.head
        m!"cannot havoc `{target.componentName}`: its type{indentExpr ty}\ndepends on the values of earlier indices"
    Term.exprToSyntax pickType

private def withHavocPick (component : StateComponent) (target : Target)
    (caps : Array (Option Name)) (k : Term → DoElabM Expr) : DoElabM Expr := do
  let capitalArgs := target.args.zipIdx.filterMap fun (arg, i) =>
    if caps[i]!.isSome then some arg else none
  let componentType ← Term.elabType (← component.typeStx)
  let pickType ← havocPickType target componentType caps
  withFreshPick target pickType capitalArgs k

/-- Havoc a `let mut` local: bind a fresh pick narrowed to the universal
dimensions of the local's type, then reuse the ordinary local-assignment path
(a capital in a local tuple update is a universal update). -/
private def elabLocalHavoc (decl : LocalDecl) (target : Target)
    (caps : Array (Option Name)) (ref : Syntax) (dec : DoElemCont) : DoElabM Expr := do
  let pickType ← havocPickType target (← instantiateMVars decl.type) caps
  let capitalArgs := target.args.zipIdx.filterMap fun (arg, i) =>
    if caps[i]!.isSome then some arg else none
  withFreshPick target pickType capitalArgs fun rhs =>
    -- The havoc entry point already ran the capital analysis once; reuse it.
    elabAnalyzedLocalAssignment target caps rhs ref dec

/-- Havoc is a narrowed pick followed by an ordinary assignment. Targets
resolve under the same local-precedence rule as `:=`, and the capital
analysis runs exactly once. -/
@[doElem_elab havocAssignment]
def elabHavoc : DoElab := fun stx dec => do
  let ctx ← requireVeilDoBlock
  let `(doElem| $lhs:term := *) := stx | throwUnsupportedSyntax
  let target ← parseTarget lhs
  let dec := openStateAfter ctx.mod dec
  do
    let caps ← implicitCapitals ctx target.args
    checkRepeatedCapitals target caps
    match ← resolveAssignmentTarget ctx target with
    | .local =>
      let some decl ← findUserLocal? target.head.getId
        | throwErrorAt target.head "internal error: havoc target resolved to a missing local"
      elabLocalHavoc decl target caps stx dec
    | .state component =>
      withHavocPick component target caps fun rhs =>
        openStateAround ctx.mod do
          elabAnalyzedStateAssignment ctx.mod component target caps rhs stx dec

end Action.DoElab
end Veil
