/-
Copyright (c) 2023 Kyle Miller. All rights reserved.
Released under Apache 2.0 license as described in LICENSE.
Adapted from Mathlib.Tactic.DeriveFintype: only constructor enumeration.
-/
import Veil.Util.GeneratedNames
namespace Veil.Deriving
open Lean Elab Meta Command
initialize registerTraceClass `veil.deriving.enum
def mkEnumList (declName : Name) : CommandElabM Unit := do
  let indVal ← getConstInfoInduct declName
  let levels := indVal.levelParams.map Level.param
  let ctorIdxName := declName.mkStr "ctorIdx"
  let enumListName := generatedName `Enumeration declName `enumList
  let ctorThmName := generatedName `Enumeration declName `enumList_getElem?_ctorIdx_eq
  let enumListNodupName := generatedName `Enumeration declName `enumList_nodup
  liftTermElabM <| Term.withoutErrToSorry do
    do -- Define `enumList` enumerating all constructors
      trace[veil.deriving.enum] "defining {enumListName}"
      let type := mkConst declName levels
      let listType ← mkAppM ``List #[type]
      let listNil ← mkAppOptM ``List.nil #[some type]
      let listCons name xs := mkAppM ``List.cons #[mkConst name levels, xs]
      let enumList ← indVal.ctors.foldrM (listCons · ·) listNil
      addAndCompile <| Declaration.defnDecl
        { name := enumListName
          levelParams := indVal.levelParams
          safety := DefinitionSafety.safe
          hints := ReducibilityHints.abbrev
          type := listType
          value := enumList }
      modifyEnv (addProtected · enumListName)
      addDocStringCore enumListName s!"A list enumerating every element of the type, \
        which are all zero-argument constructors. (Generated by the Veil enumeration deriving handler.)"
    do -- Prove that this list is in `ctorIdx` order
      trace[veil.deriving.enum] "proving {ctorThmName}"
      let goalStx ← `(term| ∀ (x : $(← Term.exprToSyntax <| mkConst declName levels)),
        $(mkIdent enumListName)[$(mkIdent ctorIdxName) x]? = some x)
      let goal ← Term.elabTerm goalStx (mkSort .zero)
      let pf ← Term.elabTerm (← `(term| by intro x; cases x <;> rfl)) goal
      Term.synthesizeSyntheticMVarsNoPostponing
      addAndCompile <| Declaration.thmDecl
        { name := ctorThmName
          levelParams := indVal.levelParams
          type := ← instantiateMVars goal
          value := ← instantiateMVars pf }
      modifyEnv (addProtected · ctorThmName)
    do -- Use this theorem to prove `enumList` has no duplicates
      trace[veil.deriving.enum] "proving {enumListNodupName}"
      let enum ← Term.exprToSyntax <| mkConst enumListName levels
      let goal ← Term.elabTerm (← `(term| List.Nodup $enum)) (mkSort .zero)
      let n : TSyntax `term := quote indVal.numCtors
      let pf ← Term.elabTerm (← `(term| by
                  apply List.Pairwise.of_map (S := (· ≠ ·)) $(mkIdent ctorIdxName) (fun _ _ h e => h (congrArg _ e))
                  have h : List.map $(mkIdent ctorIdxName) $(mkIdent enumListName)
                            = List.range $n := rfl
                  exact h ▸ List.nodup_range)) goal
      Term.synthesizeSyntheticMVarsNoPostponing
      addAndCompile <| Declaration.thmDecl
        { name := enumListNodupName
          levelParams := indVal.levelParams
          type := ← instantiateMVars goal
          value := ← instantiateMVars pf }
      modifyEnv (addProtected · enumListNodupName)

end Veil.Deriving
