import Veil

veil module AWSDnsRace

macro "PlanId" : term => `(term|Nat)
macro "NoPlan" : term => `(term|(0 : PlanId))

type Enactor

enum EnactorPC = {
  Receive,
  Apply,
  Cleanup,
  RemoveActiveDNS
}

-- maximum number of plans (bounded model checking)
immutable individual max_plan : PlanId
-- number of plan generations after which a plan can be deleted
immutable individual plan_age_threshold : PlanId

/- Route53 / regional endpoint state

  `current_plan` is the plan currently serving the regional endpoint.
  `dns_valid` says whether the endpoint has IP addresses.
-/
individual current_plan : PlanId
individual dns_valid : Bool

/- Planner / plan lifecycle state -/
individual latest_plan : PlanId           -- last plan generated by the Planner
individual highest_plan_applied : PlanId  -- highest version ever applied
relation plan_deleted : PlanId → Bool     -- set of deleted plans
relation plan_queue : PlanId → Bool       -- set of plans awaiting enactment

/-/ Enactor state -/
function enactor_processing : Enactor → PlanId        -- plan being processed by the Enactor
function enactor_pc : Enactor → EnactorPC
function cleanup_cursor : Enactor → PlanId            -- old plan being considered for cleanup

after_init {
  current_plan := NoPlan
  dns_valid := true
  latest_plan := NoPlan
  highest_plan_applied := NoPlan
  plan_deleted P := false
  plan_queue P := false
  enactor_processing E := NoPlan
  cleanup_cursor E := NoPlan
  enactor_pc E := Receive
}

procedure EnactorGoToReceive (self : Enactor) {
  cleanup_cursor self := NoPlan
  enactor_pc self := Receive
}

procedure EnactorGoToCleanup (self : Enactor) {
  cleanup_cursor self := (1 : PlanId)
  enactor_pc self := Cleanup
}


action PlannerNewPlan {
  require latest_plan < max_plan
  let new_plan := latest_plan + 1
  require new_plan ≤ max_plan
  latest_plan := new_plan
  plan_queue new_plan := true
}

action EnactorReceive (self : Enactor) {
  require ∃ (p : PlanId), plan_queue p
  require enactor_pc self = Receive

  let p :| plan_queue p = true ∧ ∀ (p'), plan_queue p' = true → p ≤ p'
  enactor_processing self := p
  enactor_pc self := Apply
  plan_queue p := false

}

action EnactorApply (self : Enactor) {
  require enactor_pc self = Apply
  let plan_to_apply := enactor_processing self

  let snapshot := current_plan

  let is_newer := (plan_to_apply > snapshot) ∨ (snapshot = NoPlan)
  let is_deleted := plan_deleted plan_to_apply
  if is_newer ∧ !is_deleted then
    current_plan := plan_to_apply
    dns_valid := true
    if plan_to_apply > highest_plan_applied then
      highest_plan_applied := plan_to_apply
    EnactorGoToCleanup self
  else
    EnactorGoToReceive self
}

action EnactorCleanupScanOne (self : Enactor) {
  require enactor_pc self = Cleanup

  let applied_plan := enactor_processing self
  let p := cleanup_cursor self

  if p < applied_plan then
    if (p ≠ NoPlan) ∧ (applied_plan - p ≥ plan_age_threshold) ∧ (!plan_deleted p) then
      plan_deleted p := true
      if current_plan = p then
        enactor_pc self := RemoveActiveDNS
    cleanup_cursor self := p + 1
  else
    EnactorGoToReceive self
}

action EnactorRemoveDNSRecords (self : Enactor) {
  require enactor_pc self = RemoveActiveDNS
  dns_valid := false
  EnactorGoToReceive self
}

safety [DnsConsistent] dns_valid = true

/- Global plan facts. -/

invariant [PlanFacts]
  latest_plan ≤ max_plan ∧
  highest_plan_applied ≤ latest_plan ∧
  current_plan = highest_plan_applied

/- Queued-plan facts. -/

invariant [QueuedPlansAreGenerated]
  plan_queue P →
    P ≠ NoPlan ∧
    P ≤ latest_plan

invariant [EnactorShape]
  (enactor_pc E = Receive ∧
   cleanup_cursor E = NoPlan)
  ∨
  (enactor_pc E = Apply ∧
   enactor_processing E ≠ NoPlan ∧
   cleanup_cursor E = NoPlan)
  ∨
  (enactor_pc E = Cleanup ∧
   enactor_processing E ≠ NoPlan ∧
   cleanup_cursor E ≠ NoPlan)

/- Per-enactor plan bounds. -/
invariant [ProcessingPlansAreGenerated]
  enactor_processing E ≤ latest_plan

invariant [CleanupBounds]
  enactor_pc E = Cleanup →
    enactor_processing E ≤ current_plan ∧
    cleanup_cursor E ≤ enactor_processing E

set_option veil.solver "grind+smt"

#gen_spec

#check_invariants

end AWSDnsRace
