module

public import Examples.TLA.BcastByz

/-!
# Unforgeability of the Byzantine broadcast protocol

This file proves, for the protocol specified in `BcastByz.lean`, the property
verified with TLAPS in `Benchmarks/TLA/bcastByz.tla`:

    THEOREM Unforg_Step4 == SpecNoBcast => []Unforg

where `SpecNoBcast == InitNoBcast /\ [][Next]_vars` and
`InitNoBcast == pc \in [ Proc -> {"V0"} ] /\ Init`: if no process receives an
INIT message, then no correct process ever accepts. The proof follows the TLAPS
proof: the inductive invariant `IndInv_Unforg_NoBcast_TLC` is established by
`InitNoBcast` (`Unforg_Step1`), preserved by every action (`Unforg_Step2_*`),
and implies `Unforg` (`Unforg_Step3`). Since `IndInv_Unforg_NoBcast_TLC` only
holds for the runs of `SpecNoBcast`, and not for those of `Spec`, it is not an
`invariant` of the specification in `BcastByz.lean`; everything here is stated
over the definitions generated by that specification.
-/

public section

namespace BcastByz

open Veil

section

variable {ρ σ process : Type} [process_dec_eq : DecidableEq process] [process_inhabited : Inhabited process]
  {procSet : Type} [procSet_dec_eq : DecidableEq procSet] [procSet_inhabited : Inhabited procSet]
  [pset : TSet process procSet]
  {PCState : Type} [PCState_dec_eq : DecidableEq PCState] [PCState_inhabited : Inhabited PCState]
  [PCState_Enum : PCState_EnumClass PCState] [processEnumerable : Veil.Enumeration process]
  {χ : State.Label → Type}
  [χ_rep : ∀ __veil_f, Veil.FieldRepresentation (State.Label.toDomain process procSet PCState __veil_f)
    (State.Label.toCodomain process procSet PCState __veil_f) (χ __veil_f)]
  [χ_rep_lawful : ∀ __veil_f, Veil.LawfulFieldRepresentation
    (State.Label.toDomain process procSet PCState __veil_f)
    (State.Label.toCodomain process procSet PCState __veil_f) (χ __veil_f) (χ_rep __veil_f)]
  [σ_sub : IsSubStateOf (State χ) σ] [ρ_sub : IsSubReaderOf (Theory process procSet PCState) ρ]

/-- `Proc == 1 .. N`, the set of all processes. -/
@[invSimp, reducible]
def Proc : procSet := pset.ofList processEnumerable.allValues

/-- The inductive invariant of the TLAPS proof, `IndInv_Unforg_NoBcast_TLC`,
conjunct by conjunct (set equalities on `Proc` are stated pointwise). -/
@[invSimp, reducible]
def IndInv_Unforg_NoBcast (th : ρ) (st : σ) : Prop :=
  let th : Theory process procSet PCState := readFrom th
  let st : State χ := getFrom st
  let Corr := @FieldRepresentation.get _ _ _ (χ_rep .Corr) st.Corr
  let Faulty := @FieldRepresentation.get _ _ _ (χ_rep .Faulty) st.Faulty
  let pc := @FieldRepresentation.get _ _ _ (χ_rep .pc) st.pc
  let sent := @FieldRepresentation.get _ _ _ (χ_rep .sent) st.sent
  let rcvd := @FieldRepresentation.get _ _ _ (χ_rep .rcvd) st.rcvd
  -- pc = [ i \in Proc |-> "V0" ]
  (∀ i, pc i = PCState_Enum.V0) ∧
  -- Corr \in SUBSET Proc
  (∀ p, pset.contains p Corr → pset.contains p Proc) ∧
  -- Cardinality( Corr ) >= N - T
  pset.count Corr ≥ th.N - th.T ∧
  -- Faulty = Proc \ Corr
  Faulty = pset.diff Proc Corr ∧
  -- \A i \in Proc : pc[i] /= "AC"
  (∀ i, pc i ≠ PCState_Enum.AC) ∧
  -- sent = {}
  sent = pset.empty ∧
  -- rcvd \in [ Proc -> sent \cup SUBSET ByzMsgs ]
  (∀ i p, pset.contains p (rcvd i) → pset.contains p Faulty)

/-- The additional initial condition of `InitNoBcast == pc \in [ Proc -> {"V0"} ] /\ Init`. -/
@[invSimp, reducible]
def NoBcast (_th : ρ) (st : σ) : Prop :=
  let st : State χ := getFrom st
  let pc := @FieldRepresentation.get _ _ _ (χ_rep .pc) st.pc
  ∀ i, pc i = PCState_Enum.V0

/-- `Unforg == (\A i \in Proc: i \in Corr => (pc[i] /= "AC"))` -/
@[invSimp, reducible]
def Unforg (_th : ρ) (st : σ) : Prop :=
  let st : State χ := getFrom st
  let Corr := @FieldRepresentation.get _ _ _ (χ_rep .Corr) st.Corr
  let pc := @FieldRepresentation.get _ _ _ (χ_rep .pc) st.pc
  ∀ i, pset.contains i Corr → pc i ≠ PCState_Enum.AC

-- The predicates with their type arguments fixed, as in the generated statements.
local notation "IndInv" => IndInv_Unforg_NoBcast (ρ := ρ) (σ := σ) (process := process) (procSet := procSet)
  (PCState := PCState) (χ := χ)
local notation "NoBcastInit" => NoBcast (ρ := ρ) (σ := σ) (process := process) (procSet := procSet)
  (PCState := PCState) (χ := χ)
local notation "UnforgP" => Unforg (ρ := ρ) (σ := σ) (process := process) (procSet := procSet)
  (PCState := PCState) (χ := χ)

/-! ### Step 1: `InitNoBcast => IndInv_Unforg_NoBcast` -/

theorem Unforg_Step1 :
    VeilM.meetsSpecificationIfSuccessfulAssuming
      (@initializer.ext ρ σ process process_dec_eq process_inhabited procSet procSet_dec_eq procSet_inhabited pset
        PCState PCState_dec_eq PCState_inhabited PCState_Enum processEnumerable χ χ_rep χ_rep_lawful σ_sub ρ_sub)
      (@Assumptions ρ process process_dec_eq process_inhabited procSet procSet_dec_eq procSet_inhabited pset PCState
        PCState_dec_eq PCState_inhabited PCState_Enum processEnumerable ρ_sub)
      (fun _ _ => True)
      (fun th st => NoBcastInit th st → IndInv th st) := by
  unveil
  intro hcount hno
  have hdist := PCState_EnumClass.distinct (self := PCState_Enum)
  simp only [distinctN, distinctPairs] at hdist
  obtain ⟨h01, _, h0A, _⟩ := hdist
  -- `NoBcast` forces `V1Set` to be empty
  have hV : ∀ i, TSet.contains i V1Set = false := fun i => by
    cases h : TSet.contains i V1Set
    · rfl
    · exact absurd (hno i h).symm h01
  refine ⟨hno, ?_, ?_, ?_, ?_⟩
  · intro p _
    exact (TSet.contains_ofList p Enumeration.allValues).mpr (Veil.Enumeration.complete p)
  · omega
  · intro i
    simp only [hV i, Bool.false_eq_true, if_false]
    exact h0A
  · intro p hp
    rw [TSet.empty_contains] at hp
    exact absurd hp Bool.false_ne_true

/-! ### Step 2: `IndInv_Unforg_NoBcast /\ [Next]_vars => IndInv_Unforg_NoBcast'` -/

omit process_inhabited procSet_dec_eq procSet_inhabited in
/-- The cardinality argument of the TLAPS proof: under the invariant, the
messages a process holds after a receive step (`rcvd self ∪ newMessages`) all
come from faulty processes (`sent = {}`), and `|Faulty| = |Proc| - |Corr| ≤ T`. -/
theorem count_rcvd_le_T (N T : Nat) (Corr Faulty sent rcvd newMessages : procSet)
    (hN : pset.count Proc = N)
    (hCorr : ∀ p, pset.contains p Corr = true → pset.contains p Proc = true)
    (hcount : N ≤ pset.count Corr + T)
    (hFaulty : Faulty = pset.diff Proc Corr)
    (hsent : sent = pset.empty)
    (hrcvd : ∀ p, pset.contains p rcvd = true → pset.contains p Faulty = true)
    (hnew : TSet.isSubset newMessages (pset.union sent Faulty)) :
    pset.count (pset.union rcvd newMessages) ≤ T := by
  have hsub : TSet.isSubset Corr Proc := hCorr
  have h1 := TSet.count_diff_add_count_of_subset Proc Corr hsub
  have hF : pset.count Faulty ≤ T := by rw [hFaulty]; omega
  have hsub2 : TSet.isSubset (pset.union rcvd newMessages) Faulty := by
    intro p hp
    rw [TSet.contains_union, Bool.or_eq_true] at hp
    rcases hp with hp | hp
    · exact hrcvd p hp
    · have := hnew p hp
      rwa [TSet.contains_union, hsent, TSet.empty_contains, Bool.false_or] at this
  have := TSet.count_le_of_subset _ _ hsub2
  omega

-- `UNCHANGED vars`: the stuttering step.
theorem Unforg_Step2_Stutter :
    VeilM.meetsSpecificationIfSuccessfulAssuming
      (@Stutter.ext ρ σ process process_dec_eq process_inhabited procSet procSet_dec_eq procSet_inhabited pset PCState
        PCState_dec_eq PCState_inhabited PCState_Enum processEnumerable χ χ_rep χ_rep_lawful σ_sub ρ_sub)
      (@Assumptions ρ process process_dec_eq process_inhabited procSet procSet_dec_eq procSet_inhabited pset PCState
        PCState_dec_eq PCState_inhabited PCState_Enum processEnumerable ρ_sub)
      IndInv IndInv := by
  unveil
  exact hinv

-- `UponV1` requires `pc[self] = "V1"`, which contradicts `pc = [i \in Proc |-> "V0"]`.
theorem Unforg_Step2_UponV1 (self : process) :
    VeilM.meetsSpecificationIfSuccessfulAssuming
      (@Step_UponV1.ext ρ σ process process_dec_eq process_inhabited procSet procSet_dec_eq procSet_inhabited
        pset PCState PCState_dec_eq PCState_inhabited PCState_Enum processEnumerable χ χ_rep χ_rep_lawful σ_sub ρ_sub
        self)
      (@Assumptions ρ process process_dec_eq process_inhabited procSet procSet_dec_eq procSet_inhabited pset PCState
        PCState_dec_eq PCState_inhabited PCState_Enum processEnumerable ρ_sub)
      IndInv IndInv := by
  unveil
  intro _ hV1 _ _
  have hV0 : st.pc self = PCState_EnumClass.V0 := hinv.1 self
  have hd := PCState_Enum.distinct
  rw [distinctN_cons] at hd
  have hne : PCState_EnumClass.V0 ≠ PCState_EnumClass.V1 := hd.2 _ (by simp)
  exact absurd (hV0.symm.trans hV1) hne

-- `UponNonFaulty` requires at least `N - 2*T` ECHO messages, but under the invariant a
-- process can only have received messages from the (at most `T`) faulty processes, and `N > 3*T`.
theorem Unforg_Step2_UponNonFaulty (self : process) :
    VeilM.meetsSpecificationIfSuccessfulAssuming
      (@Step_UponNonFaulty.ext ρ σ process process_dec_eq process_inhabited procSet procSet_dec_eq procSet_inhabited
        pset PCState PCState_dec_eq PCState_inhabited PCState_Enum processEnumerable χ χ_rep χ_rep_lawful σ_sub ρ_sub
        self)
      (@Assumptions ρ process process_dec_eq process_inhabited procSet procSet_dec_eq procSet_inhabited pset PCState
        PCState_dec_eq PCState_inhabited PCState_Enum processEnumerable ρ_sub)
      IndInv IndInv := by
  unveil
  intro _ _ newMessages hnew hge _
  obtain ⟨_, hCorr, hcount, hFaulty, _, hsent, hrcvd⟩ := hinv
  have := count_rcvd_le_T th.N th.T st.Corr st.Faulty st.sent (st.rcvd self) newMessages
    has.2.2 hCorr hcount hFaulty hsent (hrcvd self) hnew
  omega

-- `UponAcceptNotSentBefore` requires at least `N - T` ECHO messages: same argument.
theorem Unforg_Step2_UponAcceptNotSentBefore (self : process) :
    VeilM.meetsSpecificationIfSuccessfulAssuming
      (@Step_UponAcceptNotSentBefore.ext ρ σ process process_dec_eq process_inhabited procSet procSet_dec_eq procSet_inhabited
        pset PCState PCState_dec_eq PCState_inhabited PCState_Enum processEnumerable χ χ_rep χ_rep_lawful σ_sub ρ_sub
        self)
      (@Assumptions ρ process process_dec_eq process_inhabited procSet procSet_dec_eq procSet_inhabited pset PCState
        PCState_dec_eq PCState_inhabited PCState_Enum processEnumerable ρ_sub)
      IndInv IndInv := by
  unveil
  intro _ _ newMessages hnew hge
  obtain ⟨_, hCorr, hcount, hFaulty, _, hsent, hrcvd⟩ := hinv
  have := count_rcvd_le_T th.N th.T st.Corr st.Faulty st.sent (st.rcvd self) newMessages
    has.2.2 hCorr hcount hFaulty hsent (hrcvd self) hnew
  omega

-- `UponAcceptSentBefore` requires `pc[self] = "SE"`, which contradicts `pc = [i \in Proc |-> "V0"]`.
theorem Unforg_Step2_UponAcceptorSentBefore (self : process) :
    VeilM.meetsSpecificationIfSuccessfulAssuming
      (@Step_UponAcceptorSentBefore.ext ρ σ process process_dec_eq process_inhabited procSet procSet_dec_eq procSet_inhabited
        pset PCState PCState_dec_eq PCState_inhabited PCState_Enum processEnumerable χ χ_rep χ_rep_lawful σ_sub ρ_sub
        self)
      (@Assumptions ρ process process_dec_eq process_inhabited procSet procSet_dec_eq procSet_inhabited pset PCState
        PCState_dec_eq PCState_inhabited PCState_Enum processEnumerable ρ_sub)
      IndInv IndInv := by
  unveil
  intro _ hSE _ _ _
  have hV0 : st.pc self = PCState_EnumClass.V0 := hinv.1 self
  have hd := PCState_Enum.distinct
  rw [distinctN_cons] at hd
  have hne : PCState_EnumClass.V0 ≠ PCState_EnumClass.SE := hd.2 _ (by simp)
  exact absurd (hV0.symm.trans hSE) hne

/-! ### Step 3: `IndInv_Unforg_NoBcast => Unforg` -/

omit process_dec_eq process_inhabited procSet_dec_eq procSet_inhabited PCState_dec_eq PCState_inhabited
  χ_rep_lawful in
theorem Unforg_Step3 (th : ρ) (st : σ) : IndInv th st → UnforgP th st := by
  intro h i _
  exact h.2.2.2.2.1 i

end

/-! ### Step 4: `SpecNoBcast => []Unforg` -/

section SpecNoBcast

variable (process procSet PCState : Type) [Inhabited process] [Inhabited procSet] [Inhabited PCState]
  [pset : TSet process procSet] [PCState_Enum : PCState_EnumClass PCState]
  [processEnumerable : Veil.Enumeration process]

-- The generated transition system decides equality on the sorts classically.
open Classical

local notation "Th" => Theory process procSet PCState
local notation "Chi" => FieldAbstractType process procSet PCState
local notation "St" => State (FieldAbstractType process procSet PCState)

/-- `SpecNoBcast == InitNoBcast /\ [][Next]_vars`: the transition system generated from the
specification, with its initial states restricted to those satisfying `NoBcast`. -/
noncomputable def SpecNoBcast : RelationalTransitionSystem Th St (Label process procSet PCState) :=
  let sys := relationalTransitionSystem process procSet PCState
  { sys with
    init := fun th st => sys.init th st ∧
      NoBcast (ρ := Th) (σ := St) (process := process) (procSet := procSet) (PCState := PCState) (χ := Chi) th st }

/-- A WP-style specification of an action, turned into a statement about its transition relation. -/
theorem meetsSpecificationIfSuccessfulAssuming_toTransitionDerived {ρ σ : Type}
    (act : VeilM Mode.external ρ σ Unit) (assu : ρ → Prop) (pre post : SProp ρ σ)
    (h : act.meetsSpecificationIfSuccessfulAssuming assu pre post) :
    ∀ th st st', assu th → pre th st → act.toTransitionDerived th st st' → post th st' := by
  intro th st st' hassu hpre htr
  have h' := (Transition.meetsSpecificationIfSuccessful_eq act (fun th st => assu th ∧ pre th st) post).mpr h
  rw [VeilM.toTransitionDerived_sound] at h'
  exact h' th st st' ⟨hassu, hpre⟩ htr

/-- `THEOREM Unforg_Step4 == SpecNoBcast => []Unforg`: every reachable state of `SpecNoBcast`
satisfies `Unforg`. -/
theorem Unforg_Step4 (th : Th) (st : St) :
    (SpecNoBcast process procSet PCState).reachable th st →
    Unforg (ρ := Th) (σ := St) (process := process) (procSet := procSet) (PCState := PCState) (χ := Chi) th st := by
  intro hreach
  apply Unforg_Step3
  induction hreach with
  | init s has hinit =>
    obtain ⟨hinit, hnb⟩ := hinit
    simp only [SpecNoBcast, relationalTransitionSystem, Init] at has hinit
    rw [← initializer.ext.derived_eq] at hinit
    exact meetsSpecificationIfSuccessfulAssuming_toTransitionDerived _ _ _ _ Unforg_Step1 th default s has trivial hinit hnb
  | step s s' hreach hnext ih =>
    have has := RelationalTransitionSystem.reachable_assumptions _ _ _ hreach
    simp only [SpecNoBcast, relationalTransitionSystem] at has
    obtain ⟨label, htr⟩ := hnext
    simp only [SpecNoBcast, relationalTransitionSystem, Next] at htr
    cases label with
    | Stutter =>
      exact meetsSpecificationIfSuccessfulAssuming_toTransitionDerived _ _ _ _ Unforg_Step2_Stutter th s s' has ih htr
    | Step_UponV1 self =>
      exact meetsSpecificationIfSuccessfulAssuming_toTransitionDerived _ _ _ _ (Unforg_Step2_UponV1 self) th s s' has ih htr
    | Step_UponNonFaulty self =>
      exact meetsSpecificationIfSuccessfulAssuming_toTransitionDerived _ _ _ _ (Unforg_Step2_UponNonFaulty self) th s s' has ih htr
    | Step_UponAcceptNotSentBefore self =>
      exact meetsSpecificationIfSuccessfulAssuming_toTransitionDerived _ _ _ _ (Unforg_Step2_UponAcceptNotSentBefore self) th s s' has ih htr
    | Step_UponAcceptorSentBefore self =>
      exact meetsSpecificationIfSuccessfulAssuming_toTransitionDerived _ _ _ _ (Unforg_Step2_UponAcceptorSentBefore self) th s s' has ih htr

end SpecNoBcast

end BcastByz

end
